# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, dev ]

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [ setup ]

    steps:
      - name: Build and Test
        run: ./gradlew build
  publish:
    name: Publish
    if: github.event_name == 'push' && contains(github.ref, 'main')
    needs: [ setup, build ]
    runs-on: ubuntu-latest

    steps:
      - name: Test
        env:
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        run: ./gradlew publish -DmavenCentralRepositoryUsername=$SONATYPE_USERNAME -DmavenCentralRepositoryPassword=$SONATYPE_PASSWORD
